#!/bin/bash

function installApi {
  if [ ! -d "./yichang-backend" ]; then
  cd $smartPath && git clone https://code.aliyun.com/yichang/yichang-backend.git
  fi
  cd yichang-backend && git checkout dev && docker-compose up -d && ./smart composer && chmod +x vendor/bin/* && cd $smartPath
}

function startApi {
  cd yichang-backend && git checkout dev && docker-compose up -d && cd $smartPath
}

function stopApi {
  cd yichang-backend && git checkout dev && docker-compose stop && cd $smartPath
}

function clearApi {
  cd yichang-backend && git checkout dev && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function updateApi {
  cd yichang-backend && git checkout dev && git pull origin dev && cd $smartPath
}
