#!/bin/bash

function installBasement {
  installMysql
  installMongo
  installRabbitmq
  installFluentd
}

function installMysql {
  createFolder 'basement/mysql'
  cp ./smart-scripts/shell/composefiles/mysql.yml basement/mysql/docker-compose.yml
  cd basement/mysql && docker-compose up -d && cd $smartPath
}

function installMongo {
  createFolder 'basement/mongo'  
  cp ./smart-scripts/shell/composefiles/mongo.yml basement/mongo/docker-compose.yml
  cd basement/mongo && docker-compose up -d && cd $smartPath
}

function installRabbitmq {
  createFolder 'basement/rabbitmq'
  cp ./smart-scripts/shell/composefiles/rabbitmq.yml basement/rabbitmq/docker-compose.yml
  cd basement/rabbitmq && docker-compose up -d && cd $smartPath
}

function installFluentd {
  createFolder 'basement/fluentd'
  cp ./smart-scripts/shell/composefiles/fluentd.yml basement/fluentd/docker-compose.yml
  cp ./smart-scripts/shell/config/fluentd.conf basement/fluentd/
  cd basement/fluentd && docker-compose up -d && cd $smartPath
}

function startBasement {
  cd basement/mysql && docker-compose up -d && cd $smartPath
  cd basement/rabbitmq && docker-compose up -d && cd $smartPath
  cd basement/mongo && docker-compose up -d && cd $smartPath
  cd basement/fluentd && docker-compose up -d && cd $smartPath
}

function clearBasement {
  cd basement/mysql && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
  cd basement/rabbitmq && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
  cd basement/mongo && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
  cd basement/fluentd && docker-compose stop && docker-compose rm -f && docker-compose pull && cd $smartPath
}

function stopBasement {
  cd basement/mysql && docker-compose stop && cd $smartPath
  cd basement/rabbitmq && docker-compose stop && cd $smartPath
  cd basement/mongo && docker-compose stop && cd $smartPath
  cd basement/fluentd && docker-compose stop && cd $smartPath
}

function createFolder {
  if [ ! -d "./$1" ]; then
    mkdir -p $1
  fi
}
